using System.Collections.Generic;
using System.Linq;
using System.Web;
using TP09.Models;
using Newtonsoft.Json;

namespace TP09.Models
{
    public class BD
    {

        public BD()
        {
            //completar
        }
        public List<Categoria> ObtenerCategorias()
        {

        }
        public List<Pregunta> ObtenerPreguntas(int Categoria)
        {

        }
        public List<Respuesta> ObtenerRespuestas(int idPregunta)
        {

        }

        //mas los metodos privados necesarios
    }
}